# To build: sudo docker build -t local_test_machine1 .

FROM ubuntu:xenial

RUN	apt-get update && apt-get install -y \
	net-tools \
	iproute \
	inetutils-ping \
	iperf3 \
	nmap \
	ssh \
         iproute \
         inetutils-ping \
         hping3 \
         curl \
         python

CMD /bin/bash


